// import './demo/更新子元素'
// import './demo/vnode描述其他类型元素'
// import './demo/简单diff'
// import './demo/渲染组件'
// import './demo/setup函数'
// import './demo/emit'
// import './demo/onMounted'
// import './demo/异步组件'
// import './demo/slot'
// import './demo/函数组件'
// import './demo/KeepAlive'
// import './demo/Teleport'
import './demo/Transition'
